### ISSUE TITLE
弹幕量过大时导致卡住

### ISSUE THREAD

**Issue by ChaosTong** [BacooTang/douyu-danmu#1]
弹幕量过大时导致卡住，比如五五开自证没开挂的时候，
不知道是不是这个错误导致的
RangeError: Index out of range
    at checkOffset (buffer.js:972:11)
    at Buffer.readInt16LE (buffer.js:1107:5)
    at douyu_danmu._on_data (/Users/chaostong/Developer/Crawler/Crawler-JS/node_modules/_douyu-danmu@1.0.2@douyu-danmu/index.js:114:36)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)

**Comment by BacooTang** [comment]
你这用的是1.0.2版本吧，这是旧版本的bug,理论在1.1.0版本已经修复,请升级到1.1.2最新版测试~

**Comment by ChaosTong** [comment]
1.1.2 版本没有这个问题了。👌

**Comment by BacooTang** [comment]
五五开解释得太好笑了。。
